### ISSUE TITLE
Alias build peculiarities into a custom `massa-sc-script` NPM package

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa-sc-template#3]
Currently, we have:

https://github.com/massalabs/massa-sc-template/blob/477e853ec69000ff32ae6fa4c0890fe88294ec76/package.json#L9-L20

I suggest something like:

```json
 "scripts": { 
   "build": "massa-sc-scripts build", 
   "start": "massa-sc-scripts start",
   "test": "massa-sc-scripts test",
   "clean": "massa-sc-scripts clean",
 }, 
```

It will allow user to simply update their SDK by updating `massa-sc-scripts` version in dependencies!

**Comment by damip** [comment]
Good let's do it :)

**Comment by yvan-sraka** [comment]
I just published the package https://github.com/massalabs/massa-sc-scripts :tada:!
