### ISSUE TITLE
Remove `include_base64.js` build hack

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-sc-template#5]
If you use `node massa_tools/include_base64.js assembly/create_sc.ts` on the following file, the base64 encoding of `get_string.wasm` will be included which is not what we want!
```js
import { create_sc, include_base64 } from "./massa";

export function main(_args: string): i32 {
    // Create smart contract "get_string"
    // const bytes = include_base64('./build/get_string.wasm');
    // create_sc(bytes);
    return 0;
}
```

**Comment by qdrn** [comment]
Btw, I think it also fails if the name contains numeric characters (e.g. `const bytes = include_base64('./build/massa20.wasm');`

**Comment by yvan-sraka** [comment]
@adrien-zinger I think, we want to get rid of `bin` directory and https://github.com/massalabs/massa-sc-template/blob/main/bin/include_base64.js!
I don't know yet how exactly, but I think we have to move this kind of logic into a `massa-sc-scripts` build custom config as described here https://github.com/massalabs/massa-sc-template/issues/3.
