### ISSUE TITLE
Error while importing index

### ISSUE THREAD

**Issue by damip** [massalabs/massa-sc-template#7]
```
massa_execution::vm: failed running bytecode in operation index 0 in block 26fFebi39UNf1xhxJiqfvy6X6UFcu8GaaAQ6BBtySHs3RekGeT: Error while importing "index"."assembly_script_print": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```

when running

```
import { print } from "massa-sc-std";

export function main(_args: string): void {
    print("Hello world!");
}
```

using the massa-sc-template project.

however, by replacing the massa-sc-std dependency by the one forked by z80 here: https://github.com/z80dev/massa-sc-std, it works

twin issue: https://github.com/massalabs/massa-sc-std/issues/5

**Comment by adrien-zinger** [comment]
Fixed since [this commit](https://github.com/massalabs/massa-sc-std/commit/75e7499fd031f6d4bd2d913e9ca16ef3168dd40a) and integrated in the npx package!
